### PR TITLE
Create bugz_test.go

### PR DESCRIPTION
**Pull request by Xeonid**

### CODE REVIEW

**Review by ngortheone — COMMENTED** [review]
Good. You covered basic scenario - all expected IDs must be found in the extracted set.

Do you think it is possible that `expectedIDs` should exactly match `ids`?
What if `ids` contains more all from `expectedIDs` and some more?

Think if there is a valid use case for that or not?

**Comment by Xeonid** [comment]
1. It is possible that expectedIDs exactly match ids if the test setup ensures that the expected user IDs and fields in expectedIDs correspond exactly to the user IDs and fields extracted by the extractIDs function from the provided Bug object.
2. If ids contains all the bugs from expectedIDs along with some additional bugs, it means that the extractIDs function is returning more results than expected. This situation could occur due to various reasons, such as a bug in the implementation of extractIDs, differences in data sources or data structures, or unexpected behaviors in the test environment.
3. The additional bugs could be used to verify the integrity and consistency of the bug database. By comparing the retrieved ids with the expectedIDs, the test can identify any discrepancies or unexpected changes in the data.

**Comment by ngortheone** [comment]
In this case the answer 2 is the most correct.
What are the consequences? How can you modify the test to account for such situation?

**Comment by Xeonid** [comment]
We can modify the test to check if all bugs in expectedIDs are present in ids. This allows for additional bugs in ids without causing test failures. Or we can add assertion to verify that there are no bugs in ids that are not present in expectedIDs.

**Comment by ngortheone** [comment]
> We can modify the test to check if all bugs in expectedIDs are present in ids. 

Don't you already do that?

```
for id, user := range expectedIDs {
		if ids[id].ID != user.ID {
			t.Errorf("extractIDs returned incorrect ID for user %d", id)
		}
	}
```

**Pull request merged**
